import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";
import next from "next";
import { Provider } from "@radix-ui/react-tooltip";
import UserDetailProvider from "./provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "AI Website Generator",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

const outfit = Outfit({subsets:['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={outfit.className}>
        <UserDetailProvider>
          {children}
          <Toaster />
        </UserDetailProvider>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
